export { default as TitleSection } from './TitleSection'
export { default as Highlight } from './Highlight'
export { default as Bold } from './Bold'
export { default as Experience } from './Experience'
export { default as DisplayLottie } from './DisplayLottie'
export { default as DisplayProject } from './DisplayProject'
